In [1]:
import numpy as np
import torch 

In [4]:
x = torch.FloatTensor(4) #입력
W = torch.FloatTensor(4,3) #가중치 Weights
b = torch.FloatTensor(3) #편향 bias
print(x)
print(W)
print(b)

tensor([0., 0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([-2.0830e-17,  1.0902e-42,  0.0000e+00])


In [7]:
def linearFunction(x,W,b):
  y = torch.matmul(x, W)+b
  return y 

In [6]:
print(W.shape, x.shape)
print(b.shape)

torch.Size([4, 3]) torch.Size([4])
torch.Size([3])


In [8]:
y = linearFunction(x, W, b)
print(y.shape)

torch.Size([3])


# 04_BUILD_NEURAL_NETWORK
- 신경망 모델을 클래스로 만들고 nn.Module을 상속받음

In [19]:
tensor.device


NameError: name 'tensor' is not defined

In [2]:
import torch.nn as nn 

In [9]:
class NeuralNetwork(nn.Module):
  def __init__(self): #초기화 메서드
    super().__init__() #다른 클래스의 속성/메소드 불러와 #신경망 계층 초기화
    self.W = torch.FloatTensor(4,3)
    self.b = torch.FloatTensor(3)
  def forward(self, x):
    y = torch.matmul(x, self.W) + self.b
    return y

In [11]:
x = torch.FloatTensor(4)
mylinear = NeuralNetwork()

y = mylinear(x)

In [12]:
print(y, y.shape)

tensor([-2.0827e-17,  1.0902e-42,  2.3694e-38]) torch.Size([3])


In [16]:
for param in mylinear.parameters():
  print(param)

# nn.Parameter 등록

In [ ]:
class NeuralNetwork(nn.Module):
  def __init__(self, input_dim, output_dim):
    super.__init__()
    self.W = nn.Parameter()
    self.b = nn.Parameter()
  def forward(self, x):
    y = torch.matmul(x, self.W)+self.b 
    return y 

In [18]:
data1 = np.array(10)
data1

array(10)

In [7]:
data1.ndim #get dimension

0

In [8]:
data1.shape

()