In [1]:
import torch
torch.__version__
#'2.2.1'

'2.2.1'

In [2]:
#Using GPU: NVIDIA GeForce MX450
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("Using GPU:", torch.cuda.get_device_name(0))
else:
    device = torch.device('cpu')
    print("Using CPU")

Using GPU: NVIDIA GeForce MX450


In [7]:
data =[
  [1,2],
  [3,4]
]
x = torch.tensor(data)
print(x.is_cuda) #False

x= x.cuda() #GPU로 옮기는 방법!!!
print(x.is_cuda) #TRUE

#다시 CPU로 옮기기
x = x.cpu()
print(x.is_cuda)

'''
주의 : 서로 다른 장치device에 있는 텐서끼리 연산 수행하면 오류!!
'''

False
True
False


# Tensor 텐서 생성
- similiar to numpy's ndarray
- '자동 미분' 기능 제공

In [11]:
import numpy as np

## scala (0D tensor)
- can make it using numpy

In [11]:
data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

10 0 ()


## vector(1D tensor)

In [3]:
data2 = torch.FloatTensor([1,2])
print(data2, data2.dim(), data2.shape)

data2 = torch.FloatTensor(3) 
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([0., 0., 0.]) 1 torch.Size([3])


## matrix (2D tensor)

In [7]:
data3 = torch.FloatTensor(3,2)
print(data3)
print(data3.dim(), data3.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 6.]])
2 torch.Size([3, 2])


In [9]:
data3 = torch.FloatTensor([[1,2],[2,3],[5,6]])
print(data3)
print(data3.dim(), data3.shape)

tensor([[1., 2.],
        [2., 3.],
        [5., 6.]])
2 torch.Size([3, 2])


## 3D tensor

## Tensor 속성

In [8]:
tensor = torch.rand(3,4)
tensor

tensor([[0.9952, 0.1009, 0.4411, 0.7019],
        [0.5939, 0.2555, 0.7407, 0.8717],
        [0.2518, 0.5918, 0.3667, 0.2298]])

In [10]:
print('shape:', tensor.shape)
print('data type:', tensor.dtype)
print('device:', tensor.device)

shape: torch.Size([3, 4])
data type: torch.float32
device: cpu


# Change array structure

 reshape

Tensor 연산 Calculations
-element wise 연산

자동 미분과 기울기Gradient

In [ ]:
torch.tensor([3.0, 4.0], requires_grad=True)

In [ ]:
torch.tensor([1.0, 2.0], requires_grad=True)