In [2]:
import torch

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("Using GPU:", torch.cuda.get_device_name(0))
else:
    device = torch.device('cpu')
    print("Using CPU")

Using GPU: NVIDIA GeForce MX450


# Tensor 생성
- similiar to numpy's ndarray

In [4]:
import numpy as np

## scala (0D tensor)
- can make it using numpy

In [11]:
data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

10 0 ()


## vector(1D tensor)

In [3]:
data2 = torch.FloatTensor([1,2])
print(data2, data2.dim(), data2.shape)

data2 = torch.FloatTensor(3) 
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([0., 0., 0.]) 1 torch.Size([3])


## matrix (2D tensor)

In [7]:
data3 = torch.FloatTensor(3,2)
print(data3)
print(data3.dim(), data3.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 6.]])
2 torch.Size([3, 2])


In [9]:
data3 = torch.FloatTensor([[1,2],[2,3],[5,6]])
print(data3)
print(data3.dim(), data3.shape)

tensor([[1., 2.],
        [2., 3.],
        [5., 6.]])
2 torch.Size([3, 2])


## 3D tensor

# Change array structure

 reshape